In [1]:
# inicio

In [7]:
#### classificação

In [13]:
from sklearn.datasets import load_iris

In [164]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

In [166]:
iris = load_iris(as_frame=True)
df_iris = iris.frame

In [168]:
df_iris

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [170]:
x_iris = df_iris.drop("target", axis = 1)
y_iris = df_iris["target"]

In [172]:
x_iris.shape, y_iris.shape

((150, 4), (150,))

In [174]:
x_train_iris, x_test_iris, y_train_iris, y_test_iris = train_test_split(x_iris, y_iris,
                                                                       test_size = 0.3,
                                                                       random_state = 0)

In [176]:
x_train_iris.shape, x_test_iris.shape, y_train_iris.shape, y_test_iris.shape

((105, 4), (45, 4), (105,), (45,))

In [178]:
modelo_tree =  DecisionTreeClassifier(random_state = 0)

In [180]:
modelo_tree

DecisionTreeClassifier(random_state=0)

In [182]:
modelo_tree.fit(x_train_iris, y_train_iris,)

DecisionTreeClassifier(random_state=0)

In [184]:
y_preds_iris = modelo_tree.predict(x_test_iris)

In [186]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [188]:
acuracia_tree = accuracy_score(y_test_iris, y_preds_iris)

In [190]:
print('Acuracia arvore de decisao: ', acuracia_tree)

Acuracia arvore de decisao:  0.9777777777777777

In [192]:
from sklearn import tree

In [196]:
from sklearn import tree

In [198]:
#### REGRESSÃO LOGÍSTICA

In [200]:
from sklearn.linear_model import LogisticRegression

In [202]:
modelo_rl = LogisticRegression(random_state = 0)

In [204]:
# Instanciar o modelo
modelo_rl = LogisticRegression()

modelo_rl.fit(x_train_iris, y_train_iris)

In [ ]:
# Fazer previsões
y_preds_rl_iris = modelo_rl.predict(x_test_iris)

# Exibir previsões
print(y_preds_rl_iris)

In [ ]:
acuracia_rl = accuracy_score(y_test_iris, y_preds_rl_iris)

In [ ]:
print('Acuracia', acuracia_rl)

In [119]:
# Random Forest

In [77]:
modelo_rf = RandomForestClassifier(n_estimators = 100, random_state = 0)

In [87]:
modelo_rf.fit = (x_train_iris, y_train_iris)

In [ ]:
y_preds_iris_rf = modelo_rf.predict(x_test_iris)

In [ ]:
acuracia_rf = accuracy_score(y_test_iris, y_preds_iris_rf)

In [ ]:
print('Acuracia', acuracia_rf)

In [101]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [103]:
breast_cancer = load_breast_cancer(as_frame = True)
df_breast = breast_cancer.frame

In [107]:
df_breast

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1